version: "3"

vars:
  BUILD_DIR: "build"
  TOOLCHAIN_DIR: ".toolchain"
  TOOLCHAIN_FILE: ".toolchain/toolchain.cmake"
  SHADER_OUTPUT_DIR: "modules/sidecar/include/gen"

  GIT_SHORT_SHA:
    sh: git rev-parse --short HEAD

  DTTR_VERSION: "{{.DTTR_VERSION | default .GIT_SHORT_SHA}}"

  DTTR_MODDING: "OFF"

  DOCKER: podman
  CONTAINER_IMAGE: dttr-toolchain
  CONTAINERFILE_BUILD: "build.Containerfile"

tasks:
  build:
    deps:
      - build-asm
      - build-compat
      - build-shaders
      - format
      - setup-build
    cmds:
      - cmake --build {{ .BUILD_DIR | quote }} --config Debug

  build-release:
    deps:
      - build
    cmds:
      - cmake --build {{ .BUILD_DIR | quote }} --config Release

  setup-build:
    cmds:
      - >-
        cmake -G "Ninja Multi-Config" -B {{ .BUILD_DIR | quote }}
        -DCMAKE_TOOLCHAIN_FILE={{ .TOOLCHAIN_FILE | quote }}
        -DDTTR_VERSION="{{ .DTTR_VERSION }}"
        -DDTTR_MODDING={{ .DTTR_MODDING }}

  clean:
    cmds:
      - rm -rf {{ .BUILD_DIR | quote }}
      - rm -rf {{ .TOOLCHAIN_DIR | quote }}

  build-asm:
    vars:
      ASM_DIR: "{{ .ROOT_DIR }}/modules/loader/asm"
      OUTPUT_FILE: "{{ .ROOT_DIR }}/modules/loader/include/gen/asm.h"
      BIN_DIR:
        sh: mktemp -d
    cmds:
      - |
        echo "Assembling {{ .ASM_DIR | quote }} into {{ .OUTPUT_FILE | quote }}" && \
        bash ./scripts/build-asm.sh {{ .ASM_DIR | quote }} {{ .OUTPUT_FILE | quote }} {{ .BIN_DIR | quote }}

  build-compat:
    vars:
      INPUT_FILE: "{{ .ROOT_DIR }}/modules/loader/compat/packed_sdb.bin"
      OUTPUT_FILE: "{{ .ROOT_DIR }}/modules/loader/include/gen/packed_sdb.h"
    cmds:
      - |
        echo "Embedding {{ .INPUT_FILE | quote }} into {{ .OUTPUT_FILE | quote }}" && \
        bash ./scripts/build-compat.sh {{ .INPUT_FILE | quote }} {{ .OUTPUT_FILE | quote }}

  build-shaders:
    cmds:
      - cmd: 'echo "WARN: Skipping SDL3 GPU shaders on macOS because shadercross is unavailable. Consider using container builds instead."'
        platforms: [darwin]
      - cmd: |
          echo "Compiling SDL3 GPU shaders to {{ .SHADER_OUTPUT_DIR | quote }}" && \
          bash ./scripts/build-shaders.sh {{ .SHADER_OUTPUT_DIR | quote }}
        platforms: [linux, windows]
      - cmd: |
          echo "Generating OpenGL shaders to {{ .SHADER_OUTPUT_DIR | quote }}" && \
          bash ./scripts/build-opengl-shaders.sh {{ .SHADER_OUTPUT_DIR | quote }}

  container-build:
    cmds:
      - >-
        {{ .DOCKER }} build -t "{{ .CONTAINER_IMAGE }}" -f {{ .CONTAINERFILE_BUILD | quote }}
        {{ .ROOT_DIR | quote }}
      - >-
        bash ./scripts/container-build.sh
        {{ .ROOT_DIR | quote }}
        {{ .DOCKER | quote }}
        {{ .CONTAINER_IMAGE | quote }}
        {{ .TOOLCHAIN_DIR | quote }}
        "build-container"
        "{{ .DTTR_VERSION }}"
        "{{ .GIT_SHORT_SHA }}"
        {{ .DTTR_MODDING }}

  format:
    cmds:
      - echo "Running formatter"
      - |
        find ./modules/loader ./modules/sidecar ./modules/common ./sdk/components \
          -path '*/include/gen/*' -prune -o \
          \( -iname '*.h' -o -iname '*.c' \) -print | xargs clang-format -i

  generate-docs:
    cmds:
      - doxygen doxyfile.ini
