#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <asm-dir> <output-header>" >&2
  exit 1
fi

asm_dir=$(cd "$1" && pwd)
output_file=$2
bin_dir="$(mktemp -d)"
trap 'rm -rf "$bin_dir"' EXIT

mkdir -p "$bin_dir" "$(dirname "$output_file")"
echo "Assembling \"$asm_dir\" into \"$output_file\""
cd "$bin_dir"
for asm_file in "$asm_dir"/*.asm; do
  [ -e "$asm_file" ] || continue
  base_name="$(basename "${asm_file%.asm}")"
  nasm --reproducible -Ox -f bin "$asm_file" -l "${base_name}.lst" -o "$base_name"
  tmp_header="${base_name}.h.tmp"
  xxd -i "$base_name" > "$tmp_header"
  {
    echo "// Auto-generated by modules/loader/scripts/generate-asm-header.sh. Do not edit."
    echo "#ifndef DTTR_GENERATED_ASM_H"
    echo "#define DTTR_GENERATED_ASM_H"
    echo
    sed -E \
      -e 's/^unsigned char /const unsigned char /' \
      -e 's/^unsigned int /const unsigned int /' \
      "$tmp_header"
    echo
    echo "#endif // DTTR_GENERATED_ASM_H"
  } > "$output_file"
  clang-format -i "$output_file"
done
