#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <packed-sdb-bin> <output-header>" >&2
  exit 1
fi

input_file=$1
output_file=$2
tmp_header="$(mktemp)"
trap 'rm -f "$tmp_header"' EXIT

mkdir -p "$(dirname "$output_file")"
echo "Embedding \"$input_file\" into \"$output_file\""
xxd -i "$input_file" > "$tmp_header"
{
  echo "// Auto-generated by modules/loader/scripts/generate-packed-sdb-header.sh. Do not edit."
  echo "#ifndef DTTR_GENERATED_PACKED_SDB_H"
  echo "#define DTTR_GENERATED_PACKED_SDB_H"
  echo
  echo "#include <stddef.h>"
  echo
  sed -E \
    -e 's/^unsigned char [^ ]+\[\]/static const unsigned char packed_sdb[]/' \
    -e 's/^unsigned int [^ ]+/static const size_t packed_sdb_len/' \
    "$tmp_header"
  echo
  echo "#endif // DTTR_GENERATED_PACKED_SDB_H"
} > "$output_file"
clang-format -i "$output_file"
