build-dir := env_var_or_default("BUILD_DIR", "build")
build-config-debug := env_var_or_default("BUILD_CONFIG_DEBUG", "Debug")
test-max-parallel := env_var_or_default("TEST_JOBS", "8")

blueprints:
    cd "{{invocation_directory()}}" && cmake --build "{{build-dir}}" --config "{{build-config-debug}}" --target dttr_pcdogs_generated_headers dttr_sdk_bundle_header

blueprints-check:
    cd "{{invocation_directory()}}" && ctest --test-dir "{{build-dir}}" -C "{{build-config-debug}}" --output-on-failure -R "^(dttr_pcdogs_generated_headers|dttr_sdk_bundle_header)$"

test:
    cd "{{invocation_directory()}}" && cmake --build "{{build-dir}}" --config "{{build-config-debug}}" --parallel "{{test-max-parallel}}" --target dttr_sdk_tests
    cd "{{invocation_directory()}}" && ctest --test-dir "{{build-dir}}" -C "{{build-config-debug}}" --output-on-failure --parallel "{{test-max-parallel}}" -R "^(dttr_sdk_|dttr_pcdogs_)"
