#!/usr/bin/env bash

set -euo pipefail

out_dir="${1:-${SHADER_OUTPUT_DIR:-${SHADER_BUILD_DIR:-sidecar/include/gen}}}"
bin_dir="${out_dir}/shaders"
src_dir="sidecar/shaders/sdl3gpu"
header_path="${out_dir}/sdl3gpu_shaders.h"
shadercross="$(command -v shadercross || command -v sdl_shadercross || true)"

[ -d "$src_dir" ] || { echo "Missing shader source dir: $src_dir" >&2; exit 1; }
[ -n "$shadercross" ] || { echo "Missing shadercross/sdl_shadercross" >&2; exit 1; }

rm -rf "$bin_dir"
mkdir -p "$bin_dir"

shader_stage_for_stem() {
  case "$1" in
    *.vert) printf '%s\n' vertex ;;
    *.frag) printf '%s\n' fragment ;;
    *.comp) printf '%s\n' compute ;;
    *) return 1 ;;
  esac
}

for spv in "$src_dir"/*.spv; do
  [ -f "$spv" ] || continue
  cp -f "$spv" "$bin_dir/"
done

for glsl in "$src_dir"/*.glsl; do
  [ -f "$glsl" ] || continue
  stem="$(basename "$glsl" .glsl)"
  stage="$(shader_stage_for_stem "$stem")" || continue

  spv="${bin_dir}/${stem}.spv"
  glslc -fshader-stage="$stage" -o "$spv" "$glsl"
  "$shadercross" -s SPIRV -d DXIL -t "$stage" -e main -o "${bin_dir}/${stem}.dxil" "$spv"
done

{
  echo "/* Auto-generated by scripts/build-shaders.sh. Do not edit. */"
  echo "#ifndef DTTR_GENERATED_SHADERS_H"
  echo "#define DTTR_GENERATED_SHADERS_H"
  echo
  find "$bin_dir" -maxdepth 1 -type f \( -name '*.spv' -o -name '*.dxil' \) | sort | while read -r bin; do
    symbol="$(basename "$bin" | tr '.' '_')"
    xxd -i -n "$symbol" "$bin" | sed -E \
      -e 's/^unsigned char /const unsigned char /' \
      -e 's/^unsigned int /const unsigned int /'
    echo
  done
  echo "#endif /* DTTR_GENERATED_SHADERS_H */"
} > "$header_path"
