#!/usr/bin/env bash
set -euo pipefail

[ "$#" -eq 2 ] || { echo "Usage: $0 <input_bin> <output_header>" >&2; exit 1; }

input_file="$1"
output_dir="$(mkdir -p "$(dirname "$2")"; cd "$(dirname "$2")" && pwd)"
output_file="${output_dir}/$(basename "$2")"

tmp_header="$(mktemp)"
trap 'rm -f "$tmp_header"' EXIT
xxd -i "$input_file" > "$tmp_header"

{
  echo "/* Auto-generated by scripts/build-compat.sh. Do not edit. */"
  echo "#ifndef DTTR_GENERATED_PACKED_SDB_H"
  echo "#define DTTR_GENERATED_PACKED_SDB_H"
  echo
  echo "#include <stddef.h>"
  echo
  sed -E \
    -e 's/^unsigned char [^ ]+\[\]/static const unsigned char g_packed_sdb[]/' \
    -e 's/^unsigned int [^ ]+/static const size_t g_packed_sdb_len/' \
    "$tmp_header"
  echo
  echo "#endif /* DTTR_GENERATED_PACKED_SDB_H */"
} > "$output_file"
clang-format -i "$output_file"
