#!/usr/bin/env bash

set -euo pipefail

out_dir="${1:-${SHADER_OUTPUT_DIR:-${SHADER_BUILD_DIR:-sidecar/include/gen}}}"
src_dir="sidecar/shaders/opengl"
header_path="${out_dir}/opengl_shaders.h"

[ -d "$src_dir" ] || { echo "Missing OpenGL shader source dir: $src_dir" >&2; exit 1; }

mkdir -p "$out_dir"

emit_string_literal() {
  local file="$1"
  while IFS= read -r line || [ -n "$line" ]; do
    printf '\t"%s\\n"\n' "$(printf '%s' "$line" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  done < "$file"
}

emit_shader_source() {
  local file stem

  file="$1"
  stem="$(basename "$file" .glsl | tr '.' '_')"

  echo "static const char *S_OPENGL_${stem^^}_SOURCE ="
  emit_string_literal "$file"
  echo ";"
  echo
}

{
  echo "/* Auto-generated by scripts/build-opengl-shaders.sh. Do not edit. */"
  echo "#ifndef DTTR_GENERATED_OPENGL_SHADERS_H"
  echo "#define DTTR_GENERATED_OPENGL_SHADERS_H"
  echo

  for glsl in "$src_dir"/*.vert.glsl "$src_dir"/*.frag.glsl; do
    [ -f "$glsl" ] || continue
    emit_shader_source "$glsl"
  done

  echo "#endif /* DTTR_GENERATED_OPENGL_SHADERS_H */"
} > "$header_path"
clang-format -i "$header_path"

echo "Generated $header_path"
