#!/usr/bin/env bash
set -euo pipefail

[ "$#" -eq 3 ] || { echo "Usage: $0 <asm_dir> <output_file> <bin_dir>" >&2; exit 1; }

asm_dir="$(cd "$1" && pwd)"
output_file="$(mkdir -p "$(dirname "$2")"; cd "$(dirname "$2")" && pwd)/$(basename "$2")"
bin_dir="$3"
mkdir -p "$bin_dir"

cd "$bin_dir"
for asm_file in "$asm_dir"/*.asm; do
  [ -e "$asm_file" ] || continue
  base="$(basename "${asm_file%.asm}")"
  nasm --reproducible -O0 -f bin "$asm_file" -l "$base.lst" -o "$base"
  tmp_h="$base.h.tmp"
  xxd -i "$base" > "$tmp_h"
  {
    echo "/* Auto-generated by scripts/build-asm.sh. Do not edit. */"
    echo "#ifndef DTTR_GENERATED_ASM_H"
    echo "#define DTTR_GENERATED_ASM_H"
    echo
    cat "$tmp_h"
    echo
    echo "#endif /* DTTR_GENERATED_ASM_H */"
  } > "$output_file"
  rm -f "$tmp_h"
  cat "$base.lst"
done
