#!/usr/bin/env bash
set -euo pipefail

[ "$#" -eq 3 ] || { echo "Usage: $0 <asm_dir> <output_file> <bin_dir>" >&2; exit 1; }

asm_dir="$(cd "$1" && pwd)"
output_dir="$(mkdir -p "$(dirname "$2")"; cd "$(dirname "$2")" && pwd)"
output_file="${output_dir}/$(basename "$2")"
bin_dir="$3"

mkdir -p "$bin_dir"
cd "$bin_dir"

for asm_file in "$asm_dir"/*.asm; do
  [ -e "$asm_file" ] || continue
  base_name="$(basename "${asm_file%.asm}")"
  nasm --reproducible -Ox -f bin "$asm_file" -l "${base_name}.lst" -o "$base_name"
  tmp_header="${base_name}.h.tmp"
  xxd -i "$base_name" > "$tmp_header"

  {
    echo "/* Auto-generated by scripts/build-asm.sh. Do not edit. */"
    echo "#ifndef DTTR_GENERATED_ASM_H"
    echo "#define DTTR_GENERATED_ASM_H"
    echo
    sed -E \
      -e 's/^unsigned char /const unsigned char /' \
      -e 's/^unsigned int /const unsigned int /' \
      "$tmp_header"
    echo
    echo "#endif /* DTTR_GENERATED_ASM_H */"
  } > "$output_file"
  clang-format -i "$output_file"

  rm -f "$tmp_header"
done
