#!/usr/bin/env bash

set -euo pipefail

out_dir="${1:-${SHADER_OUTPUT_DIR:-${SHADER_BUILD_DIR:-sidecar/include/gen}}}"
bin_dir="${out_dir}/shaders"
src_dir="sidecar/shaders"
header="${out_dir}/shaders.h"
shadercross="$(command -v shadercross || command -v sdl_shadercross || true)"

[ -d "$src_dir" ] || { echo "Missing shader source dir: $src_dir" >&2; exit 1; }
[ -n "$shadercross" ] || { echo "Missing shadercross/sdl_shadercross" >&2; exit 1; }

rm -rf "$bin_dir"
mkdir -p "$bin_dir"

find "$src_dir" -maxdepth 1 -type f -name '*.spv' -exec cp -f {} "$bin_dir/" \;

find "$src_dir" -maxdepth 1 -type f -name '*.glsl' | sort | while read -r glsl; do
  stem="$(basename "$glsl" .glsl)"
  case "$stem" in
    *.vert) stage=vertex ;;
    *.frag) stage=fragment ;;
    *.comp) stage=compute ;;
    *) continue ;;
  esac

  spv="${bin_dir}/${stem}.spv"
  glslc -fshader-stage="$stage" -o "$spv" "$glsl"
  "$shadercross" -s SPIRV -d DXIL -t "$stage" -e main -o "${bin_dir}/${stem}.dxil" "$spv"
  "$shadercross" -s SPIRV -d MSL  -t "$stage" -e main -o "${bin_dir}/${stem}.msl" "$spv"
done

{
  echo "/* Auto-generated by scripts/build-shaders.sh. Do not edit. */"
  echo "#ifndef DTTR_GENERATED_SHADERS_H"
  echo "#define DTTR_GENERATED_SHADERS_H"
  echo
  find "$bin_dir" -maxdepth 1 -type f \( -name '*.spv' -o -name '*.dxil' -o -name '*.msl' \) | sort | while read -r bin; do
    symbol="$(basename "$bin" | tr '.' '_')"
    xxd -i -n "$symbol" "$bin" | sed -E \
      -e 's/^unsigned char /const unsigned char /' \
      -e 's/^unsigned int /const unsigned int /'
    echo
  done
  echo "#endif /* DTTR_GENERATED_SHADERS_H */"
} > "$header"
