#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <manifest_file> <out_dir>" >&2
  exit 1
fi

manifest_file="$1"
out_dir="$2"
mkdir -p "$out_dir"

ret_size() {
  [[ "$1" =~ @([0-9]+)$ ]] && printf '%s' "${BASH_REMATCH[1]}" || printf '0'
}

write_asm() {
  {
    echo "/* Auto-generated by scripts/generate-support-stubs.sh. Do not edit. */"
    echo ".text"
    echo ".globl _DllMainCRTStartup@12"
    echo "_DllMainCRTStartup@12:"
    echo $'\tmovl $1, %eax'
    echo $'\tret $12'
    echo

    for size in "$@"; do
      echo ".globl _dttr_stub_ret${size}"
      echo "_dttr_stub_ret${size}:"
      echo $'\txorl %eax, %eax'
      [ "$size" = "0" ] && echo $'\tret' || echo $'\tret $'"${size}"
      echo
    done
  } > "$out_dir/dttr_support_stub_entry.s"
}

write_def_header() {
  local dll="$1"
  current_def="$out_dir/${dll}.def"
  {
    echo "; Auto-generated by scripts/generate-support-stubs.sh. Do not edit."
    echo "LIBRARY \"${dll}.dll\""
    echo "EXPORTS"
  } > "$current_def"
}

current_def=""
declare -A ret_sizes=([0]=1)

while IFS= read -r raw_line || [ -n "$raw_line" ]; do
  line="${raw_line%%#*}"
  line="${line//$'\r'/}"
  line="${line#${line%%[![:space:]]*}}"
  line="${line%${line##*[![:space:]]}}"
  [ -n "$line" ] || continue

  if [[ "$line" =~ ^\[([^]]+)\]$ ]]; then
    write_def_header "${BASH_REMATCH[1]}"
    continue
  fi

  if [ -z "$current_def" ]; then
    echo "Export without DLL section: $line" >&2
    exit 1
  fi
  size="$(ret_size "$line")"
  ret_sizes[$size]=1
  echo "  ${line}=dttr_stub_ret${size}" >> "$current_def"
done < "$manifest_file"

mapfile -t sorted_ret_sizes < <(printf '%s\n' "${!ret_sizes[@]}" | sort -n)
write_asm "${sorted_ret_sizes[@]}"
