#!/usr/bin/env python3
"""Generate import-library stubs for bundled support DLLs."""

from __future__ import annotations

import re
import sys
from pathlib import Path

RET_SIZE_RE = re.compile(r"@(\d+)$")
SUPPORT_STUB_MANIFEST: dict[str, tuple[str, ...]] = {
    # DLL stubs satisfy PCDOGS static imports until sidecar hooks are installed.
    "mss32": (
        "_AIL_allocate_sample_handle@4",
        "_AIL_close_stream@4",
        "_AIL_end_sample@4",
        "_AIL_get_preference@4",
        "_AIL_init_sample@4",
        "_AIL_open_stream@12",
        "_AIL_pause_stream@8",
        "_AIL_release_sample_handle@4",
        "_AIL_sample_playback_rate@4",
        "_AIL_sample_status@4",
        "_AIL_set_digital_master_volume@8",
        "_AIL_set_preference@8",
        "_AIL_set_sample_file@12",
        "_AIL_set_sample_loop_count@8",
        "_AIL_set_sample_pan@8",
        "_AIL_set_sample_playback_rate@8",
        "_AIL_set_sample_volume@8",
        "_AIL_set_stream_loop_count@8",
        "_AIL_set_stream_volume@8",
        "_AIL_shutdown@0",
        "_AIL_start_sample@4",
        "_AIL_start_stream@4",
        "_AIL_startup@0",
        "_AIL_stop_sample@4",
        "_AIL_stream_status@4",
        "_AIL_waveOutClose@4",
        "_AIL_waveOutOpen@16",
    ),
    "winstr": (
        "Movie_GetCurrentFrame",
        "Movie_GetSoundChannels",
        "Movie_GetSoundPrecision",
        "Movie_GetSoundRate",
        "Movie_GetTotalFrames",
        "Movie_GetXSize",
        "Movie_GetYSize",
        "Movie_SetSyncAdjust",
    ),
    "winplay": (
        "Player_InitMovie",
        "Player_InitMoviePlayback",
        "Player_InitPlaybackMode",
        "Player_InitSound",
        "Player_InitSoundSystem",
        "Player_InitVideo",
        "Player_InitVideoSystem",
        "Player_MapVideo",
        "Player_PlayFrame",
        "Player_ReturnPlaybackMode",
        "Player_ShutDownMovie",
        "Player_ShutDownSound",
        "Player_ShutDownSoundSystem",
        "Player_ShutDownVideo",
        "Player_ShutDownVideoSystem",
        "Player_StartTimer",
        "Player_StopTimer",
    ),
}


def ret_size(symbol: str) -> int:
    match = RET_SIZE_RE.search(symbol)
    return int(match.group(1)) if match else 0


def write_def(out_dir: Path, dll: str, exports: tuple[str, ...]) -> None:
    lines = [
        f"; Auto-generated by scripts/generate-support-stubs.py. Do not edit.",
        f'LIBRARY "{dll}.dll"',
        "EXPORTS",
    ]
    lines.extend(f"  {symbol}=dttr_stub_ret{ret_size(symbol)}" for symbol in exports)
    (out_dir / f"{dll}.def").write_text("\n".join(lines) + "\n")


def write_asm(out_dir: Path, sizes: set[int]) -> None:
    lines = [
        "# Auto-generated by scripts/generate-support-stubs.py. Do not edit.",
        ".text",
        ".globl _DllMainCRTStartup@12",
        "_DllMainCRTStartup@12:",
        "\tmovl $1, %eax",
        "\tret $12",
        "",
    ]

    for size in sorted(sizes):
        lines.extend(
            [
                f".globl _dttr_stub_ret{size}",
                f"_dttr_stub_ret{size}:",
                "\txorl %eax, %eax",
                "\tret" if size == 0 else f"\tret ${size}",
                "",
            ]
        )

    (out_dir / "dttr_support_stub_entry.s").write_text("\n".join(lines) + "\n")


def generate(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    ret_sizes: set[int] = {0}
    for dll, exports in SUPPORT_STUB_MANIFEST.items():
        ret_sizes.update(ret_size(symbol) for symbol in exports)
        write_def(out_dir, dll, exports)

    write_asm(out_dir, ret_sizes)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f"Usage: {argv[0]} <out_dir>", file=sys.stderr)
        return 1

    generate(Path(argv[1]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
