#!/usr/bin/env python3
"""Generate PCDOGS C/CMake test surfaces from Python blueprints."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True

from codegen import c_mask, c_sig, load_python_module

try:
    from mako.template import Template
except ImportError as exc:
    raise SystemExit(
        "generate_tests.py requires Mako; install it or enter the Nix dev shell."
    ) from exc

ENUM_PREFIXES = {
    "required": "DTTR_TEST_PCDOGS_REQUIRED",
    "cc": "DTTR_PCDOGS_CC",
    "hook": "DTTR_PCDOGS_HOOK",
}


def c_ident(name: str) -> str:
    """Convert blueprint names into C-safe identifiers for generated test fixtures."""

    ident = "".join(ch if ch.isalnum() else "_" for ch in name)
    return ident if ident and not ident[0].isdigit() else f"_{ident}"


def prefixed_enum(kind: str, value: object) -> str:
    return f"{ENUM_PREFIXES[kind]}_{str(value).upper()}"


def required_enum(required: object) -> str:
    return prefixed_enum("required", required)


def cc_enum(cc: object) -> str:
    return prefixed_enum("cc", cc)


def hook_enum(kind: object) -> str:
    return prefixed_enum("hook", kind)


def typed_params(fn: object) -> list[object]:
    """Return typed parameters for ABI checks against recovered signatures."""

    return list(fn.m_typed.m_params if fn.m_typed else [])


def abi_stack_bytes(fn: object) -> int:
    """Compute expected stack cleanup bytes from reverse-engineered calling convention metadata."""

    params = typed_params(fn)
    stack_bytes = len(params) * 4
    if str(fn.m_cc) == "fastcall":
        stack_bytes = max(0, stack_bytes - min(2, len(params)) * 4)
    return stack_bytes


ROWS_TEMPLATE = Template(
    """// Generated by generate_tests.py.

% for symbol, blueprint in blueprints:
static const blueprint_signature ${symbol}_SIGNATURES[] = {
% for sig in blueprint.m_signatures:
\t{"${sig.m_name}", (const uint8_t *)${c_sig(sig.m_pattern)}, ${c_mask(sig.m_pattern)}, ${required_enum(sig.m_required)}},
% endfor
};

static const blueprint_function ${symbol}_FUNCTIONS[] = {
% for fn in blueprint.m_functions:
<% patch_size = fn.m_hook.m_patch_size %>\
<% entry_patch_size = fn.m_hook.m_entry_patch_size or patch_size %>\
\t{"${fn.m_name}", (const uint8_t *)${c_sig(fn.m_pattern)}, ${c_mask(fn.m_pattern)}, ${required_enum(fn.m_required)}, ${int(fn.m_match_offset)}, ${cc_enum(fn.m_cc)}, ${hook_enum(fn.m_hook.m_kind)}, ${int(patch_size)}u, ${int(entry_patch_size)}u, ${len(typed_params(fn))}u, ${abi_stack_bytes(fn)}u},
% endfor
};

% endfor
""".lstrip(),
    strict_undefined=True,
)


def render(template: Template, **kwargs: object) -> str:
    """Render one generated test artifact with stable newline handling for CMake checks."""

    text = template.render_unicode(
        c_mask=c_mask,
        c_sig=c_sig,
        required_enum=required_enum,
        cc_enum=cc_enum,
        hook_enum=hook_enum,
        typed_params=typed_params,
        abi_stack_bytes=abi_stack_bytes,
        int=int,
        len=len,
        **kwargs,
    )
    return text if text.endswith("\n") else f"{text}\n"


def load_blueprints(paths: list[Path]) -> list[tuple[str, object]]:
    """Load stable and unstable blueprint objects for generated signature test rows."""

    blueprints: list[tuple[str, object]] = []
    for path in paths:
        module = load_python_module(path)
        blueprint = getattr(module, "BLUEPRINT", None)
        if blueprint is None:
            blueprint = getattr(module, "stable", None) or getattr(
                module, "unstable", None
            )
        if blueprint is None:
            raise SystemExit(f"{path} does not define a blueprint")
        blueprints.append((c_ident(path.stem).upper(), blueprint))
    return blueprints


def write_if_changed(path: Path, text: str) -> None:
    """Avoid timestamp churn by writing generated test files only when content changes."""

    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text() if path.exists() else ""
    if old != text:
        path.write_text(text)


def main() -> int:
    """Generate blueprint-driven C and CMake fixtures used by the SDK signature tests."""

    parser = argparse.ArgumentParser()
    parser.add_argument("--rows-output", required=True, type=Path)
    parser.add_argument("blueprints", nargs="+", type=Path)
    args = parser.parse_args()

    blueprints = load_blueprints(args.blueprints)
    write_if_changed(args.rows_output, render(ROWS_TEMPLATE, blueprints=blueprints))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
