#!/usr/bin/env python3
"""Generate versioned PCDOGS SDK SymbolManifest JSON from SDK blueprints."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import replace
from pathlib import Path

from codegen import load_python_module, write_or_check
from generate_headers import (
    BUILD_MASK_BITS,
    attach_symbol_metadata,
    arg_name,
    build_mask_bits,
    c_public_token,
    c_type,
    data_write_policy,
    load_blueprint,
    param_type_name,
    pcdogs_type_name,
    row_doc,
    SymbolDocKind,
    symbol_doc,
    type_row_kind,
    validate_blueprint,
)
from symbol_manifest import (
    MANIFEST_FILENAME,
    SCHEMA_FILENAME,
    SCHEMA_VERSION,
    SUPPORTED_BUILDS,
    AnalysisFunctionCallXRef,
    AnalysisUnresolved,
    EmbeddedAnalysisXRefFrom,
    EmbeddedAnalysisXRefTo,
    EmbeddedComputedXRefFrom,
    EmbeddedComputedXRefTo,
    KIND_ORDER,
    ComputedDataSymbol,
    ComputedDataXRef,
    ComputedFunction,
    ComputedFunctionXRef,
    ComputedSignature,
    ComputedSymbols,
    ComputedType,
    ComputedXRefs,
    DataResolver,
    FunctionPrototype,
    FunctionResolver,
    ManifestCounts,
    ManifestParam,
    PatchSizes,
    ResolvedAddress,
    SymbolAnalysis,
    SymbolEntry,
    SymbolKindAnalysis,
    SymbolKindEntry,
    SymbolManifest,
    SymbolTarget,
    SupportedBuild,
    UnresolvedSymbol,
    symbol_manifest_schema,
)

ANALYSIS_SECTIONS = (
    ("signature", "signatures"),
    ("function", "functions"),
    ("data", "data"),
)

BLUEPRINT_DERIVED_KEYS = {
    "abi_status",
    "callable",
    "cc",
    "doc",
    "hook",
    "match_offset",
    "pattern",
    "public",
    "required",
    "supported_builds",
    "typed",
    "write_policy",
    "xrefs",
}
SDK_FIELD_NAMES = (
    ("id", "id"),
    ("symbol_index", "symbol_index"),
    ("accessor", "accessor"),
    ("sdk_id", "sdk_id"),
    ("symbol_id", "symbol_id"),
    ("sdk_name", "name"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate PCDOGS SDK SymbolManifest JSON from Python blueprints.",
    )
    parser.add_argument("blueprint", type=Path, nargs="?", default=None)
    parser.add_argument("--metadata-dir", type=Path, default=None)
    parser.add_argument("--sdk-version", default=None)
    parser.add_argument("--sdk-abi-version", default=None)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    parser.add_argument(
        "--function-call-xrefs",
        action="append",
        type=Path,
        default=[],
        help="JSON call xrefs generated by generate_function_call_xrefs.py",
    )
    parser.add_argument(
        "--symbol-addresses",
        action="append",
        type=Path,
        default=[],
        help="JSON symbol addresses generated by resolve_symbol_addresses.py",
    )
    return parser.parse_args()


def sdk_root() -> Path:
    return Path(__file__).resolve().parent.parent


def repo_root() -> Path:
    return sdk_root().parent.parent


def parse_sdk_abi_version() -> int:
    text = (sdk_root() / "include/dttr_versions.h.in").read_text()
    match = re.search(r"^#define\s+DTTR_SDK_ABI_VERSION\s+(\d+)u?", text, re.MULTILINE)

    if match is None:
        raise ValueError("dttr_versions.h.in missing DTTR_SDK_ABI_VERSION")

    return int(match.group(1))


def git_commit() -> str | None:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=repo_root(),
            text=True,
            capture_output=True,
            check=True,
        )

    except (FileNotFoundError, subprocess.CalledProcessError):
        return None

    commit = result.stdout.strip()
    return commit or None


def load_authored_blueprint(path: Path) -> object:
    module = load_python_module(path, "manifest_blueprint_source")
    blueprint = getattr(module, "BLUEPRINT", None)

    if blueprint is None:
        raise ValueError(f"blueprint module does not define BLUEPRINT: {path}")

    return blueprint


def supported_builds(value: object) -> list[str]:
    bits = build_mask_bits(value)
    return [name for name in SUPPORTED_BUILDS if bits & BUILD_MASK_BITS[name]]


def function_accessor(name: object) -> str:
    return f"DTTR_PCDOGS_F_{c_public_token(name)}"


def data_accessor(name: object) -> str:
    return f"DTTR_PCDOGS_D_{c_public_token(name)}"


UNDOCUMENTED_TEXT = "Not yet documented."


def doc_text(value: object | None) -> str | None:
    if value is None:
        return None
    text = " ".join(str(value).split())
    if not text or text == UNDOCUMENTED_TEXT:
        return None
    return text


def model_row(row: object, *, exclude: set[str] | None = None) -> dict[str, object]:
    if hasattr(row, "model_dump"):
        return row.model_dump(
            mode="json",
            by_alias=True,
            exclude=exclude or set(),
            exclude_none=False,
        )
    raise TypeError(f"manifest row does not support model_dump: {row!r}")


def without_name(row: object) -> dict[str, object]:
    return model_row(row, exclude={"name"})


def param_metadata(param: object) -> ManifestParam:
    if pair := param_type_name(param):
        type_, name = pair
        return ManifestParam(
            name=str(name),
            type=c_type(type_),
            docs=doc_text(getattr(param, "doc", None)),
        )
    return ManifestParam(name=arg_name(param), type=c_type(param))


def function_resolver(row: object) -> FunctionResolver:
    return FunctionResolver(
        pattern=row.pattern,
        match_offset=int(row.match_offset),
    )


def computed_function(row: object) -> ComputedFunction:
    typed = row.typed

    if typed is None:
        raise ValueError(f"function is missing typed metadata: {row.name}")

    return ComputedFunction(
        id=int(row.public_index),
        symbol_index=int(row.index),
        name=str(row.name),
        accessor=function_accessor(row.name),
        prototype=FunctionPrototype(
            return_type=c_type(typed.return_type),
            params=[param_metadata(param) for param in typed.params],
            calling_convention=typed.abi,
            abi_status=row.abi_status,
        ),
        builds=supported_builds(row.supported_builds),
        callable=bool(typed.callable),
        resolver=function_resolver(row),
        hook_kind=typed.hook_kind,
        patch_sizes=PatchSizes(
            patch_size=int(row.hook.patch_size),
            entry_patch_size=int(row.hook.entry_patch_size),
        ),
        docs=doc_text(symbol_doc(SymbolDocKind.FUNCTION, row)),
        unstable=bool(row.unstable),
        sdk_id=f"DTTR_PCDOGS_FUNCTION_{row.symbol_id}",
        symbol_id=f"DTTR_PCDOGS_SYMBOL_FUNCTION_ID_{row.symbol_id}",
    )


def computed_data_resolver(row: object) -> DataResolver | None:
    typed = row.typed

    if typed is None:
        return None

    return DataResolver(
        kind=typed.resolver,
        ref_function=str(typed.ref_function),
        instr_offset=int(typed.instr_off),
        addr_offset=int(typed.addr_off),
        indirections=int(typed.indirections),
    )


def computed_data(row: object) -> ComputedDataSymbol:
    policy = data_write_policy(row).removeprefix("DTTR_PCDOGS_WRITE_POLICY_").lower()
    return ComputedDataSymbol(
        id=int(row.public_index),
        symbol_index=int(row.public_index),
        name=str(row.name),
        accessor=data_accessor(row.name),
        type=c_type(row.typed.type) if row.typed else None,
        builds=supported_builds(row.supported_builds),
        resolver=computed_data_resolver(row),
        write_policy=policy,
        docs=doc_text(symbol_doc(SymbolDocKind.GLOBAL, row)),
        unstable=bool(row.unstable),
        sdk_id=f"DTTR_PCDOGS_DATA_{row.symbol_id}",
        symbol_id=f"DTTR_PCDOGS_SYMBOL_DATA_ID_{row.symbol_id}",
    )


def computed_type(row: object) -> ComputedType:
    kind = type_row_kind(row).value
    return ComputedType(
        name=str(row.name),
        kind=kind,
        sdk_name=pcdogs_type_name(row.name),
        size=getattr(row, "size", None),
        docs=doc_text(row_doc(row)),
        unstable=bool(getattr(row, "unstable", False)),
    )


def computed_signature(row: object) -> ComputedSignature:
    return ComputedSignature(
        name=str(row.name),
        pattern=str(row.pattern),
        builds=supported_builds(row.required),
        docs=doc_text(getattr(row, "doc", None)),
        unstable=bool(row.unstable),
    )


def computed_function_xref(row: object) -> ComputedFunctionXRef:
    return ComputedFunctionXRef(
        function=str(row.function),
        ref_function=str(row.ref_function),
        instr_offset=int(row.instr_off),
        addr_offset=int(row.addr_off),
        indirections=int(row.indirections),
        required=str(row.required),
        builds=supported_builds(row.required),
    )


def computed_data_xref(row: object) -> ComputedDataXRef:
    return ComputedDataXRef(
        data_symbol=str(row.global_name),
        function=str(row.function),
        instr_offset=int(row.instr_off),
        addr_offset=int(row.addr_off),
        indirections=int(row.indirections),
        required=str(row.required),
        builds=supported_builds(row.required),
        access=str(row.access),
    )


def computed_symbols(blueprint: object) -> ComputedSymbols:
    return ComputedSymbols(
        functions=[computed_function(row) for row in blueprint.functions],
        data=[computed_data(row) for row in blueprint.globals],
        types=[computed_type(row) for row in blueprint.structs],
        signatures=[computed_signature(row) for row in blueprint.signatures],
        xrefs=ComputedXRefs(
            functions=[computed_function_xref(row) for row in blueprint.function_xrefs],
            data=[computed_data_xref(row) for row in blueprint.xrefs],
        ),
    )


def sdk_payload(row: dict[str, object]) -> dict[str, object]:
    sdk: dict[str, object] = {}
    for source_key, sdk_key in SDK_FIELD_NAMES:
        if source_key in row:
            sdk[sdk_key] = row.pop(source_key)

    return sdk


def normalize_hook_payload(row: dict[str, object]) -> None:
    hook_kind = row.pop("hook_kind", None)
    patch_sizes = row.pop("patch_sizes", None)

    if hook_kind is None and not patch_sizes:
        return

    hook: dict[str, object] = {}
    if hook_kind is not None:
        hook["kind"] = hook_kind
    if isinstance(patch_sizes, dict):
        hook.update(patch_sizes)

    row["hook"] = hook


def normalize_calling_convention_payload(row: dict[str, object]) -> None:
    calling = row.pop("calling", None)
    if calling is not None and "calling_convention" not in row:
        row["calling_convention"] = calling


def flattened_symbol_kind(
    blueprint_row: object, computed_row: object
) -> dict[str, object]:
    row = without_name(blueprint_row)
    for key in BLUEPRINT_DERIVED_KEYS:
        row.pop(key, None)

    row.update(without_name(computed_row))
    row.pop("builds", None)
    normalize_hook_payload(row)
    normalize_calling_convention_payload(row)

    sdk = sdk_payload(row)
    if sdk:
        row["sdk"] = sdk

    return row


def set_symbol_kind(
    symbols: dict[str, dict[str, dict[str, object]]],
    *,
    name: str,
    kind: str,
    entry: dict[str, object],
) -> None:
    kinds = symbols.setdefault(name, {})
    if kind in kinds:
        raise ValueError(f"duplicate symbol kind for {name}: {kind}")
    kinds[kind] = entry


def authored_type_rows(authored: object) -> list[object]:
    rows = getattr(authored, "types", None)
    if rows is None:
        rows = getattr(authored, "structs")
    return list(rows)


def populate_symbol_kind(
    symbols: dict[str, dict[str, dict[str, object]]],
    *,
    authored_rows: object,
    computed_rows: object,
    kind: str,
) -> None:
    for blueprint_row, computed_row in zip(authored_rows, computed_rows, strict=True):
        name = str(blueprint_row.name)
        if name != computed_row.name:
            raise ValueError(
                f"{kind} computed row drift for {name}: {computed_row.name}"
            )

        set_symbol_kind(
            symbols,
            name=name,
            kind=kind,
            entry=flattened_symbol_kind(blueprint_row, computed_row),
        )


def symbol_map_base(
    *, authored: object, computed: ComputedSymbols
) -> dict[str, dict[str, dict[str, object]]]:
    symbols: dict[str, dict[str, dict[str, object]]] = {}

    sources = (
        (authored.functions, computed.functions, "function"),
        (authored.globals, computed.data, "data"),
        (authored_type_rows(authored), computed.types, "type"),
        (authored.signatures, computed.signatures, "signature"),
    )
    for authored_rows, computed_rows, kind in sources:
        populate_symbol_kind(
            symbols,
            authored_rows=authored_rows,
            computed_rows=computed_rows,
            kind=kind,
        )

    return symbols


def xref_payload(
    model: type,
    endpoint_key: str,
    endpoint: SymbolTarget,
    row: ComputedFunctionXRef | ComputedDataXRef | AnalysisFunctionCallXRef,
    *,
    include_builds: bool = False,
) -> dict[str, object]:
    payload = {
        endpoint_key: endpoint,
        "instr_offset": row.instr_offset,
        "addr_offset": row.addr_offset,
        "indirections": row.indirections,
        "access": getattr(row, "access", None),
    }
    if include_builds:
        payload["builds"] = row.builds

    return model(**payload).model_dump(mode="json", exclude_none=True)


def sort_xrefs(xrefs: list[object], endpoint_key: str) -> None:
    xrefs.sort(
        key=lambda item: (
            item[endpoint_key]["kind"],
            item[endpoint_key]["name"],
            item["instr_offset"],
            item["addr_offset"],
            item["indirections"],
            item.get("access") or "",
        )
    )


def xref_list(
    entry: dict[str, object], key: str, owner: str, *, prefix: str = ""
) -> list[object]:
    xrefs = entry.setdefault(key, [])
    if not isinstance(xrefs, list):
        raise TypeError(f"{prefix}{key} field is not a list for {owner}")

    return xrefs


def append_unique_xref(
    entry: dict[str, object],
    key: str,
    payload: dict[str, object],
    owner: str,
    *,
    prefix: str = "",
) -> list[object]:
    xrefs = xref_list(entry, key, owner, prefix=prefix)
    if payload not in xrefs:
        xrefs.append(payload)

    return xrefs


def append_computed_xref(
    symbols: dict[str, dict[str, dict[str, object]]],
    *,
    source_name: str,
    target: SymbolTarget,
    row: ComputedFunctionXRef | ComputedDataXRef,
) -> None:
    source_entry = symbols.get(source_name, {}).get("function")
    if source_entry is None:
        raise ValueError(f"xref source function is missing from symbols: {source_name}")

    target_kinds = symbols.get(target.name)
    if not target_kinds or target.kind not in target_kinds:
        raise ValueError(
            f"xref target is missing from symbols: {target.kind}:{target.name}"
        )

    source = SymbolTarget(kind="function", name=source_name)
    append_unique_xref(
        source_entry,
        "xrefs_to",
        xref_payload(
            EmbeddedComputedXRefTo, "target", target, row, include_builds=True
        ),
        source_name,
    )

    target_entry = target_kinds[target.kind]
    append_unique_xref(
        target_entry,
        "xrefs_from",
        xref_payload(
            EmbeddedComputedXRefFrom, "source", source, row, include_builds=True
        ),
        f"{target.kind}:{target.name}",
    )

    # Keep per-build analysis entries self-contained. Top-level xrefs_to/from
    # remain the aggregate SDK-summary view; analysis.<build>.xrefs_to/from is
    # the per-build view consumed by the docs UI.
    analysis_to_payload = xref_payload(EmbeddedAnalysisXRefTo, "target", target, row)
    analysis_from_payload = xref_payload(
        EmbeddedAnalysisXRefFrom, "source", source, row
    )
    for build in row.builds:
        source_build_entry = ensure_analysis_build(
            symbols,
            name=source_name,
            kind="function",
            build=build,
        )
        analysis_xrefs_to = append_unique_xref(
            source_build_entry,
            "xrefs_to",
            analysis_to_payload,
            f"{source_name}:{build}",
            prefix="analysis ",
        )

        target_build_entry = ensure_analysis_build(
            symbols,
            name=target.name,
            kind=target.kind,
            build=build,
        )
        analysis_xrefs_from = append_unique_xref(
            target_build_entry,
            "xrefs_from",
            analysis_from_payload,
            f"{target.kind}:{target.name}:{build}",
            prefix="analysis ",
        )

        sort_xrefs(analysis_xrefs_to, "target")
        sort_xrefs(analysis_xrefs_from, "source")


def attach_computed_xrefs(
    symbols: dict[str, dict[str, dict[str, object]]], computed: ComputedSymbols
) -> None:
    for row in computed.xrefs.functions:
        append_computed_xref(
            symbols,
            source_name=row.ref_function,
            target=SymbolTarget(kind="function", name=row.function),
            row=row,
        )

    for row in computed.xrefs.data:
        append_computed_xref(
            symbols,
            source_name=row.function,
            target=SymbolTarget(kind="data", name=row.data_symbol),
            row=row,
        )


def build_key(value: object) -> str:
    key = str(value).lower()
    if key not in SUPPORTED_BUILDS:
        raise ValueError(f"unsupported analysis build key: {value}")

    return key


def ensure_analysis_build(
    symbols: dict[str, dict[str, dict[str, object]]],
    *,
    name: str,
    kind: str,
    build: str,
) -> dict[str, object]:
    kind_entry = symbols.get(name, {}).get(kind)
    if kind_entry is None:
        raise ValueError(f"analysis references unknown symbol: {kind}:{name}")

    analysis = kind_entry.setdefault("analysis", {})
    if not isinstance(analysis, dict):
        raise TypeError(f"analysis entry is not an object for {kind}:{name}")

    if "builds" in analysis:
        raise TypeError(f"analysis must be keyed directly by build for {kind}:{name}")

    entry = analysis.setdefault(build, {})
    if not isinstance(entry, dict):
        raise TypeError(
            f"analysis build entry is not an object for {kind}:{name}:{build}"
        )

    return entry


def set_resolved_analysis(
    symbols: dict[str, dict[str, dict[str, object]]], row: ResolvedAddress
) -> None:
    build = build_key(row.build)

    entry = ensure_analysis_build(
        symbols,
        name=row.name,
        kind=row.kind,
        build=build,
    )

    if "unresolved" in entry:
        raise ValueError(
            f"analysis is both resolved and unresolved: {row.kind}:{row.name}:{build}"
        )

    for key, value in (
        ("address", row.address),
        ("rva", row.rva),
        ("image_base", row.image_base),
    ):
        existing = entry.get(key)
        if existing is not None and existing != value:
            raise ValueError(
                f"conflicting analysis {key} for {row.kind}:{row.name}:{build}"
            )

        entry[key] = value


def set_unresolved_analysis(
    symbols: dict[str, dict[str, dict[str, object]]], row: UnresolvedSymbol
) -> None:
    build = build_key(row.build)

    entry = ensure_analysis_build(
        symbols,
        name=row.name,
        kind=row.kind,
        build=build,
    )

    if any(key in entry for key in ("address", "rva", "image_base")):
        raise ValueError(
            f"analysis is both resolved and unresolved: {row.kind}:{row.name}:{build}"
        )

    unresolved = AnalysisUnresolved(
        reason=row.reason,
    ).model_dump(mode="json")

    existing = entry.get("unresolved")

    if existing is not None and existing != unresolved:
        raise ValueError(
            f"conflicting unresolved analysis for {row.kind}:{row.name}:{build}"
        )

    entry["unresolved"] = unresolved


def analysis_call_xref_to_payload(row: AnalysisFunctionCallXRef) -> dict[str, object]:
    return xref_payload(
        EmbeddedAnalysisXRefTo,
        "target",
        SymbolTarget(kind="function", name=row.function),
        row,
    )


def analysis_call_xref_from_payload(row: AnalysisFunctionCallXRef) -> dict[str, object]:
    return xref_payload(
        EmbeddedAnalysisXRefFrom,
        "source",
        SymbolTarget(kind="function", name=row.ref_function),
        row,
    )


def attach_analysis_xrefs(
    symbols: dict[str, dict[str, dict[str, object]]], analysis: SymbolAnalysis
) -> None:
    for row in analysis.function_call_xrefs:
        build = build_key(row.builds)

        source_entry = ensure_analysis_build(
            symbols,
            name=row.ref_function,
            kind="function",
            build=build,
        )

        target_kinds = symbols.get(row.function)
        if not target_kinds or "function" not in target_kinds:
            raise ValueError(
                f"analysis xref target is missing from symbols: function:{row.function}"
            )

        target_entry = ensure_analysis_build(
            symbols,
            name=row.function,
            kind="function",
            build=build,
        )

        to_payload = analysis_call_xref_to_payload(row)
        from_payload = analysis_call_xref_from_payload(row)
        xrefs_to = append_unique_xref(
            source_entry,
            "xrefs_to",
            to_payload,
            f"{row.ref_function}:{build}",
            prefix="analysis ",
        )
        xrefs_from = append_unique_xref(
            target_entry,
            "xrefs_from",
            from_payload,
            f"{row.function}:{build}",
            prefix="analysis ",
        )

        sort_xrefs(xrefs_to, "target")
        sort_xrefs(xrefs_from, "source")


def finalized_symbol_map(
    *, authored: object, computed: ComputedSymbols, analysis: SymbolAnalysis
) -> dict[str, SymbolEntry]:
    raw = symbol_map_base(authored=authored, computed=computed)
    attach_computed_xrefs(raw, computed)

    for row in analysis.resolved_addresses:
        set_resolved_analysis(raw, row)

    for row in analysis.unresolved:
        set_unresolved_analysis(raw, row)

    attach_analysis_xrefs(raw, analysis)

    finalized: dict[str, SymbolEntry] = {}
    for name in sorted(raw):
        ordered: dict[str, SymbolKindEntry] = {}

        for kind in KIND_ORDER:
            if kind not in raw[name]:
                continue

            entry = raw[name][kind]
            analysis_entry = entry.get("analysis")
            payload = dict(entry)

            if analysis_entry:
                payload["analysis"] = SymbolKindAnalysis.model_validate(analysis_entry)

            ordered[kind] = SymbolKindEntry.model_validate(payload)

        finalized[name] = SymbolEntry.model_validate(ordered)

    return finalized


def omit_empty_xref_lists(payload: dict[str, object]) -> dict[str, object]:
    for kinds in payload.get("symbols", {}).values():
        for entry in kinds.values():
            for key in ("xrefs_to", "xrefs_from"):
                if entry.get(key) == []:
                    del entry[key]

            analysis = entry.get("analysis", {})
            if not isinstance(analysis, dict):
                continue
            for build_entry in analysis.values():
                if not isinstance(build_entry, dict):
                    continue

                for key in ("xrefs_to", "xrefs_from"):
                    if build_entry.get(key) == []:
                        del build_entry[key]

    return payload


def manifest_payload(manifest: SymbolManifest) -> dict[str, object]:
    return omit_empty_xref_lists(
        manifest.model_dump(mode="json", by_alias=True, exclude_none=True)
    )


def stable_first(rows: list[object]) -> list[object]:
    return sorted(rows, key=lambda row: getattr(row, "unstable", False))


def sorted_authored_blueprint(path: Path) -> object:
    blueprint = load_authored_blueprint(path)

    if hasattr(blueprint, "model_copy"):
        return blueprint.model_copy(
            update={
                "signatures": stable_first(blueprint.signatures),
                "functions": stable_first(blueprint.functions),
                "globals": stable_first(blueprint.globals),
                "types": stable_first(blueprint.types),
            }
        )

    raise TypeError(f"authored blueprint does not support model_copy: {blueprint!r}")


def normalized_combined_blueprint(path: Path) -> object:
    blueprint = load_blueprint(path)

    combined = replace(
        blueprint,
        signatures=stable_first(blueprint.signatures),
        functions=stable_first(blueprint.functions),
        globals=stable_first(blueprint.globals),
        structs=stable_first(blueprint.structs),
        external_structs=[],
    )

    attach_symbol_metadata(combined)
    validate_blueprint(combined)

    return combined


def analysis_source(payload: dict[str, object]) -> tuple[str, str, str]:
    return (
        str(payload.get("build", "")),
        str(payload.get("source_game", "")),
        str(payload.get("source_game_sha256", "")),
    )


def parse_hex_int(value: object) -> int:
    return int(str(value).strip(), 0)


def rva_value(address: object, image_base: object) -> int:
    return parse_hex_int(address) - parse_hex_int(image_base)


def iter_address_rows(
    path: Path,
) -> tuple[list[ResolvedAddress], list[UnresolvedSymbol]]:
    payload = json.loads(path.read_text())
    if not isinstance(payload, dict):
        raise ValueError(f"JSON root must be object: {path}")

    build, source_game, source_game_sha256 = analysis_source(payload)
    if "image_base" not in payload:
        raise ValueError(f"symbol address metadata missing image_base: {path}")

    image_base = parse_hex_int(payload["image_base"])
    resolved: list[ResolvedAddress] = []
    unresolved: list[UnresolvedSymbol] = []

    for kind, key in ANALYSIS_SECTIONS:
        rows = payload.get(key, {})
        if not isinstance(rows, dict):
            continue

        for name, address in sorted(rows.items()):
            address_value = parse_hex_int(address)
            resolved.append(
                ResolvedAddress(
                    kind=kind,
                    name=str(name),
                    build=build,
                    address=address_value,
                    rva=rva_value(address_value, image_base),
                    image_base=image_base,
                    source_game=source_game,
                    source_game_sha256=source_game_sha256,
                )
            )

    unresolved_payload = payload.get("unresolved", {})
    if isinstance(unresolved_payload, dict):
        for kind, key in ANALYSIS_SECTIONS:
            rows = unresolved_payload.get(key, [])
            if not isinstance(rows, list):
                continue

            for row in rows:
                if not isinstance(row, dict):
                    continue

                unresolved.append(
                    UnresolvedSymbol(
                        kind=kind,
                        name=str(row.get("name", "")),
                        build=build,
                        reason=str(row.get("reason", "")),
                        source_game=source_game,
                        source_game_sha256=source_game_sha256,
                    )
                )

    return resolved, unresolved


def function_call_rows(path: Path) -> list[AnalysisFunctionCallXRef]:
    payload = json.loads(path.read_text())
    if not isinstance(payload, dict):
        raise ValueError(f"JSON root must be object: {path}")

    build, source_game, source_game_sha256 = analysis_source(payload)
    calls = payload.get("calls", [])

    if not isinstance(calls, list):
        raise ValueError(f"function-call xref calls must be list: {path}")

    rows: list[AnalysisFunctionCallXRef] = []
    for row in calls:
        if not isinstance(row, dict):
            continue

        rows.append(
            AnalysisFunctionCallXRef(
                function=str(row.get("function", "")),
                ref_function=str(row.get("ref_function", "")),
                instr_offset=int(row.get("instr_off", 0)),
                addr_offset=int(row.get("addr_off", 0)),
                indirections=int(row.get("indirections", 0)),
                builds=str(row.get("builds") or build),
                source_game=source_game,
                source_game_sha256=source_game_sha256,
            )
        )

    return rows


def symbol_analysis(
    *, symbol_addresses: list[Path], function_call_xrefs: list[Path]
) -> SymbolAnalysis:
    resolved: list[ResolvedAddress] = []
    unresolved: list[UnresolvedSymbol] = []
    calls: list[AnalysisFunctionCallXRef] = []

    for path in symbol_addresses:
        path_resolved, path_unresolved = iter_address_rows(path)
        resolved.extend(path_resolved)
        unresolved.extend(path_unresolved)

    for path in function_call_xrefs:
        calls.extend(function_call_rows(path))

    return SymbolAnalysis(
        resolved_addresses=resolved,
        function_call_xrefs=calls,
        unresolved=unresolved,
    )


def merge_build_source(
    builds: dict[str, dict[str, str]],
    *,
    build: str,
    source_game: str,
    source_game_sha256: str,
) -> None:
    entry = builds.setdefault(build_key(build), {})

    for key, value in (
        ("source_game", source_game),
        ("source_game_sha256", source_game_sha256),
    ):
        if not value:
            continue

        existing = entry.get(key, "")
        if existing and existing != value:
            raise ValueError(f"conflicting {key} for build {build}")

        entry[key] = value


def manifest_supported_builds(analysis: SymbolAnalysis) -> dict[str, SupportedBuild]:
    builds: dict[str, dict[str, str]] = {build: {} for build in SUPPORTED_BUILDS}

    for row in [
        *analysis.resolved_addresses,
        *analysis.unresolved,
        *analysis.function_call_xrefs,
    ]:
        merge_build_source(
            builds,
            build=row.build if hasattr(row, "build") else row.builds,
            source_game=row.source_game,
            source_game_sha256=row.source_game_sha256,
        )

    return {
        build: SupportedBuild.model_validate(builds[build])
        for build in SUPPORTED_BUILDS
    }


def manifest_counts(
    *, authored: object, computed: ComputedSymbols, analysis: SymbolAnalysis
) -> ManifestCounts:
    struct_count = sum(1 for row in computed.types if row.kind == "struct")

    return ManifestCounts(
        functions=len(authored.functions),
        data_symbols=len(authored.globals),
        types=len(authored_type_rows(authored)),
        signatures=len(authored.signatures),
        structs=struct_count,
        function_xrefs=len(computed.xrefs.functions),
        data_xrefs=len(computed.xrefs.data),
        resolved_addresses=len(analysis.resolved_addresses),
        function_call_xrefs=len(analysis.function_call_xrefs),
        unresolved=len(analysis.unresolved),
    )


def symbol_manifest(
    *,
    blueprint_path: Path,
    sdk_version: str,
    sdk_abi_version: int,
    symbol_addresses: list[Path] | None = None,
    function_call_xrefs: list[Path] | None = None,
) -> SymbolManifest:
    authored = sorted_authored_blueprint(blueprint_path)
    computed = computed_symbols(normalized_combined_blueprint(blueprint_path))
    analysis = symbol_analysis(
        symbol_addresses=symbol_addresses or [],
        function_call_xrefs=function_call_xrefs or [],
    )

    return SymbolManifest(
        schema_version=SCHEMA_VERSION,
        sdk_version=sdk_version,
        sdk_abi_version=sdk_abi_version,
        supported_builds=manifest_supported_builds(analysis),
        counts=manifest_counts(authored=authored, computed=computed, analysis=analysis),
        symbols=finalized_symbol_map(
            authored=authored, computed=computed, analysis=analysis
        ),
    )


def main() -> int:
    args = parse_args()
    blueprint_path = args.blueprint or sdk_root() / "blueprints/dttr_pcdogs.py"
    metadata_dir = (
        args.metadata_dir or repo_root() / "build/modules/sdk/generated/metadata"
    )
    commit = git_commit()
    sdk_version = args.sdk_version or commit or "unknown"
    sdk_abi_version = int(args.sdk_abi_version or parse_sdk_abi_version())

    manifest = symbol_manifest(
        blueprint_path=blueprint_path,
        sdk_version=sdk_version,
        sdk_abi_version=sdk_abi_version,
        symbol_addresses=args.symbol_addresses,
        function_call_xrefs=args.function_call_xrefs,
    )

    manifest_ok = write_or_check(
        metadata_dir / MANIFEST_FILENAME,
        json.dumps(
            manifest_payload(manifest),
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        args.check,
    )
    schema_ok = write_or_check(
        metadata_dir / SCHEMA_FILENAME,
        json.dumps(symbol_manifest_schema(), indent=2, ensure_ascii=False) + "\n",
        args.check,
    )

    if not (manifest_ok and schema_ok):
        print("PCDOGS symbol metadata is stale", flush=True)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
