#!/usr/bin/env python3
"""Generate PCDOGS C/CMake test surfaces from Python blueprints."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True

from codegen import c_mask, c_sig, write_or_check
from generate_headers import load_blueprint

try:
    from mako.template import Template
except ImportError as exc:
    raise SystemExit(
        "generate_tests.py requires Mako; install it or enter the Nix dev shell."
    ) from exc

ENUM_PREFIXES = {
    "required": "DTTR_TEST_PCDOGS_REQUIRED",
    "cc": "DTTR_PCDOGS_CC",
    "hook": "DTTR_PCDOGS_HOOK",
}

X86_PARAM_TYPE_BYTES = {
    "CRT_LongDouble12": 12,
    "double": 8,
    "int64_t": 8,
    "uint64_t": 8,
    "Win32_GUID": 16,
}


def prefixed_enum(kind: str, value: object) -> str:
    return f"{ENUM_PREFIXES[kind]}_{str(value).upper()}"


def required_enum(required: object) -> str:
    return prefixed_enum("required", required)


def cc_enum(cc: object) -> str:
    return prefixed_enum("cc", cc)


def hook_enum(kind: object) -> str:
    return prefixed_enum("hook", kind)


def typed_params(fn: object) -> list[object]:
    """Return typed parameters for ABI checks against recovered signatures."""

    return list(fn.typed.params if fn.typed else [])


def function_cc(fn: object) -> object:
    return getattr(fn, "cc", None) or fn.calling_convention


def x86_stack_slot_bytes(param: object) -> int:
    """Return the x86 stack space occupied by one recovered parameter."""

    return X86_PARAM_TYPE_BYTES.get(param.type.strip(), 4)


def abi_stack_bytes(fn: object) -> int:
    """Compute expected stack cleanup bytes from reverse-engineered calling convention metadata."""

    params = typed_params(fn)
    slot_bytes = [x86_stack_slot_bytes(param) for param in params]
    stack_bytes = sum(slot_bytes)

    if str(function_cc(fn)) == "fastcall":
        register_bytes = sum([size for size in slot_bytes if size == 4][:2])
        stack_bytes -= register_bytes

    return stack_bytes


ROWS_TEMPLATE = Template(
    """// Generated by generate_tests.py.

% for symbol, blueprint in blueprints:
static const blueprint_signature ${symbol}_SIGNATURES[] = {
% for sig in blueprint.signatures:
\t{"${sig.name}", (const uint8_t *)${c_sig(sig.pattern)}, ${c_mask(sig.pattern)}, ${required_enum(sig.required)}},
% endfor
};

static const blueprint_function ${symbol}_FUNCTIONS[] = {
% for fn in blueprint.functions:
<% patch_size = fn.hook.patch_size %>\
<% entry_patch_size = fn.hook.entry_patch_size or patch_size %>\
\t{"${fn.name}", (const uint8_t *)${c_sig(fn.pattern)}, ${c_mask(fn.pattern)}, ${required_enum(fn.required)}, ${int(fn.match_offset)}, ${cc_enum(function_cc(fn))}, ${hook_enum(fn.hook.kind)}, ${int(patch_size)}u, ${int(entry_patch_size)}u, ${len(typed_params(fn))}u, ${abi_stack_bytes(fn)}u},
% endfor
};

% endfor
""".lstrip(),
    strict_undefined=True,
)


def render(template: Template, **kwargs: object) -> str:
    """Render one generated test artifact with stable newline handling for CMake checks."""

    text = template.render_unicode(
        c_mask=c_mask,
        c_sig=c_sig,
        required_enum=required_enum,
        cc_enum=cc_enum,
        hook_enum=hook_enum,
        function_cc=function_cc,
        typed_params=typed_params,
        abi_stack_bytes=abi_stack_bytes,
        int=int,
        len=len,
        **kwargs,
    )
    return text if text.endswith("\n") else f"{text}\n"


def stable_first(rows: list[object]) -> list[object]:
    return sorted(rows, key=lambda row: getattr(row, "unstable", False))


def load_blueprint_surfaces(path: Path) -> list[tuple[str, object]]:
    blueprint = load_blueprint(path)
    blueprint.signatures = stable_first(blueprint.signatures)
    blueprint.functions = stable_first(blueprint.functions)
    return [("DTTR_PCDOGS", blueprint)]


def main() -> int:
    """Generate blueprint-driven C and CMake fixtures used by the SDK signature tests."""

    parser = argparse.ArgumentParser()
    parser.add_argument("--rows-output", required=True, type=Path)
    parser.add_argument("blueprint", type=Path)
    args = parser.parse_args()

    blueprints = load_blueprint_surfaces(args.blueprint)
    write_or_check(args.rows_output, render(ROWS_TEMPLATE, blueprints=blueprints))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
