#!/usr/bin/env python3
"""Generate the single-header DttR SDK distribution surface."""

from __future__ import annotations

import argparse
from pathlib import Path

STABLE_PREFIX_HEADERS = [
    "dttr_versions.h",
    "dttr_result.h",
    "dttr_runtime.h",
    "dttr_core.h",
    "dttr_mods.h",
    "dttr_pcdogs.h",
]
UTIL_HEADER = "dttr_util.h"
UNSTABLE_HEADERS = ["dttr_util_unstable.h"]
INTERNAL_INCLUDES = {*STABLE_PREFIX_HEADERS, UTIL_HEADER, *UNSTABLE_HEADERS}


def strip_internal_includes(text: str) -> str:
    lines: list[str] = []
    skip_following_blank = False
    for line in text.splitlines():
        if skip_following_blank and not line.strip():
            continue

        skip_following_blank = False

        stripped = line.strip()
        if stripped.startswith("#include <dttr_") and stripped.endswith(".h>"):
            header = stripped.removeprefix("#include <").removesuffix(">")
            if header in INTERNAL_INCLUDES:
                skip_following_blank = bool(lines and not lines[-1].strip())
                continue

        lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def find_header(include_dirs: list[Path], header: str) -> Path:
    """Return the first matching header from the generated/source include search path."""

    for include_dir in include_dirs:
        path = include_dir / header
        if path.exists():
            return path

    searched = ", ".join(str(path) for path in include_dirs)
    raise FileNotFoundError(f"missing {header}; searched: {searched}")


def append_header(parts: list[str], include_dirs: list[Path], header: str) -> None:
    parts.append(f"// ---- {header} ----\n")
    parts.append(strip_internal_includes(find_header(include_dirs, header).read_text()))
    parts.append("\n")


def generate(include_dirs: list[Path]) -> str:
    parts = [
        "// Auto-generated by modules/sdk/scripts/join_headers.py. Do not edit.\n",
        "#ifndef DTTR_SDK_H\n",
        "#define DTTR_SDK_H\n\n",
    ]
    for header in STABLE_PREFIX_HEADERS:
        append_header(parts, include_dirs, header)

    append_header(parts, include_dirs, UTIL_HEADER)

    parts.append("#ifdef DTTR_SDK_ENABLE_UNSTABLE\n\n")

    for header in UNSTABLE_HEADERS:
        append_header(parts, include_dirs, header)

    parts.append("#endif // DTTR_SDK_ENABLE_UNSTABLE\n\n")
    parts.append("#endif // DTTR_SDK_H\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--include-dir", type=Path, action="append", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    output = generate(args.include_dir)
    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != output:
            raise SystemExit(
                f"{args.output} is stale; run modules/sdk/scripts/join_headers.py"
            )
        return 0

    args.output.write_text(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
