[project]
site_name = "102 Patches: Detours to the Rescue!"
site_description = "Documentation for DttR, an alternate entrypoint for 102 Dalmatians: Puppies to the Rescue."
site_author = "dogstuff"
site_url = "https://dogstuff.gitlab.io/detours-to-the-rescue"
copyright = "Copyright &copy; 2026 dogstuff"

docs_dir = "pages"
site_dir = "build"

repo_name = "dogstuff/detours-to-the-rescue"
repo_url = "https://gitlab.com/dogstuff/detours-to-the-rescue"
extra_css = ["assets/stylesheets/site.css"]
nav = [
  { "Home" = "index.md" },
  { "Quick Start" = [
    { "Initial Setup" = "quick-start/00-initial-setup.md" },
    { "Configuration" = "quick-start/01-configuration.md" },
    { "Installing Mods" = "quick-start/02-installing-mods.md" },
    { "Troubleshooting" = "quick-start/03-troubleshooting.md" },
  ] },
  { "Modding SDK" = [
    { "Project Setup" = "modding-sdk/00-project-setup.md" },
    { "Handling Mod Callbacks" = "modding-sdk/01-handling-mod-callbacks.md" },
    { "Working with Game Globals" = "modding-sdk/02-working-with-game-globals.md" },
    { "Calling Game Functions" = "modding-sdk/03-calling-game-functions.md" },
    { "Applying Game Patches" = "modding-sdk/04-applying-game-patches.md" },
    { "Hooking Game Functions" = "modding-sdk/05-hooking-game-functions.md" },
    { "Drawing a GUI" = "modding-sdk/06-drawing-a-gui.md" },
    { "Manually Resolving Symbols" = "modding-sdk/07-resolving-symbols.md" },
    { "SDK API Documentation" = "sdk-ref/" },
  ] },
  { "Technical Details" = [
    { "Configuration" = "technical-reference/00-configuration.md" },
    { "Patches" = "technical-reference/01-patches.md" },
    { "Compilation" = "technical-reference/02-compilation.md" },
    { "Internal Documentation" = "internal/" },
  ] },
  { "Vanilla (latest)" = "https://gitlab.com/dogstuff/detours-to-the-rescue/-/releases/permalink/latest/downloads/dttr-release.zip" },
  { "Modding (latest)" = "https://gitlab.com/dogstuff/detours-to-the-rescue/-/releases/permalink/latest/downloads/dttr-modding-release.zip" },
]

plugins = [
  { "search" = { "enabled" = true } },
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.tabs.link",
  "navigation.footer",
  "navigation.tabs",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
]

[project.extra]
generator = false

[[project.theme.palette]]
scheme = "slate"

[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.blocks.caption]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
linenums_style = "pymdownx-inline"
[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.tables]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
